org.gradle.jvmargs=-Xmx4G
android.useAndroidX=true
android.enableJetifier=true
android.enableR8.fullMode=false
android.enableDexingArtifactTransform=false
# This shall be removed, if going back. Project strucutre (click file) '17' also. JAVA_HOME is set to 17, not 11. These were the changes. SAJT
# Also, local.properties is unknown if it causes troubles. Same line is there but in possibly wrong way because of lack of escape characters.
org.gradle.java.home=C\:\\Program Files\\Java\\jdk-17